name: Veracode Flaws Report

on:
  workflow_call:
    inputs:
      policy_name:
        required: true
        type: string
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string
      sha:
        required: true
        type: string
      token:
        required: true
        type: string
      ref:
        required: true
        type: string
      create_code_scanning_alert:
        required: true
        type: boolean
      create_issue:
        required: true
        type: boolean
      check_run_id:
        required: true
        type: string
      source_repository:
          required: true
          type: string
      profile_name:
          required: true
          type: string
      break_build_policy_findings: 
          required: true
          type: string
      break_build_on_error: 
          required: true
          type: string
      filter_mitigated_flaws: 
          required: true
          type: string
      language:
        required: true
        type: string

jobs:
  code-scanning-alert:
      needs: pipeline_scan
      runs-on: ubuntu-latest
      if: ${{ inputs.create_code_scanning_alert && always() }}
      name: Create code scanning alerts
      steps:
        - name: Get scan results
          uses: actions/download-artifact@v4
          with:
            name: "Veracode Pipeline-Scan Mitigated Filtered Results"

        - name: Convert pipeline scan output to SARIF format for java language
          if: inputs.language == 'Java'
          uses: Veracode/veracode-pipeline-scan-results-to-sarif@master
          with:
            pipeline-results-json: filtered_results.json
            output-results-sarif: veracode-results.sarif
            repo_owner: ${{ inputs.owner }}
            repo_name: ${{ inputs.repo }}
            commitSHA: ${{ inputs.sha }}
            ref: ${{ inputs.ref }}
            githubToken: ${{ inputs.token }}
            source-base-path-1: 'com/:src/main/java/com/'
            source-base-path-2: 'WEB-INF:src/main/webapp/WEB-INF'

        - name: Convert pipeline scan output to SARIF format for non java language
          if: inputs.language != 'Java'
          uses: Veracode/veracode-pipeline-scan-results-to-sarif@master
          with:
            pipeline-results-json: filtered_results.json
            output-results-sarif: veracode-results.sarif
            repo_owner: ${{ inputs.owner }}
            repo_name: ${{ inputs.repo }}
            commitSHA: ${{ inputs.sha }}
            ref: ${{ inputs.ref }}
            githubToken: ${{ inputs.token }}

    create-issues:
      needs: pipeline_scan
      runs-on: ubuntu-latest
      if: ${{ inputs.create_issue && always() }}
      name: Create issues
      steps:
        - name: Get scan results
          uses: actions/download-artifact@v4
          with:
            name: 'Veracode Pipeline-Scan Mitigated Filtered Results'

        - name: Create flaws as issues for java language
          if: inputs.language == 'Java'
          uses: veracode/veracode-flaws-to-issues@v2.2.24
          with:
            scan-results-json: 'filtered_results.json'
            repo_owner: ${{ inputs.owner }}
            github-token: ${{ inputs.token }}
            repo_name: ${{ inputs.repo }}
            commitHash: ${{ inputs.sha }}
            source_base_path_1: 'com/:src/main/java/com/'
            source_base_path_2: 'WEB-INF:src/main/webapp/WEB-INF'

        - name: Create flaws as issues for non java language
          if: inputs.language != 'Java'
          uses: veracode/veracode-flaws-to-issues@v2.2.24
          with:
            scan-results-json: 'filtered_results.json'
            repo_owner: ${{ inputs.owner }}
            repo_name: ${{ inputs.repo }}
            github-token: ${{ inputs.token }}
            commitHash: ${{ inputs.sha }}